export const SET_SKILLS_DATA = 'SET_SKILLS_DATA';
export const SET_EXPERIENCE_DATA = 'SET_EXPERIENCE_DATA';
export const SET_EDUCATION_DATA = 'SET_EDUCATION_DATA';
export const SET_CERTIFICATES_DATA = 'SET_CERTIFICATES_DATA';
export const SET_PROJECTS_DATA = 'SET_CERTIFICATES_DATA';
export const SET_PROJECT_CATEGORY = 'SET_PROJECT_CATEGORY';
